### PR TITLE
Add link behavior that does not prevent default action

### PR DESCRIPTION
**Pull request by rbu**

### CODE REVIEW

**Comment by rbu** [comment]
ping, any chance of getting this merged and seeing a release?

**Comment by istvan-ujjmeszaros** [comment]
Thanks for your contribution, but I am against using links with dropdown toggles.

**Comment by dwt** [comment]
Sorry, but I'm a bit disappointed with that stance you take there. Can you at least provide the rationale you use to come to this decision?

Best Regards,
Martin Häcker

**Comment by istvan-ujjmeszaros** [comment]
Can you provide an example when that would be really useful?

**Comment by rbu** [comment]
Hey @istvan-ujjmeszaros I use this for a hover menu in a responsive page. The link leads to an overview page explaining the subsections.
On mobile, people never get to see the dropdown, they will always visit the intermediate page and can choose from there. On desktop, people can hover and directly visit the subsection they seek out or click the link and see more details.

**Comment by istvan-ujjmeszaros** [comment]
People must be very careful when using something like that. That could be done by duplicating these links, one optimized for desktop with the dropdown, and the other with simple links on mobile.
But I know how frustrating may be it when you are using a solution and the maintainer just don't want to add support for it when it could be done real easy. mdo is doing that a lot of time with Bootstrap :)
So reopening, and will merge later today or tomorrow.

**Comment by istvan-ujjmeszaros** [comment]
I am not sure if we need the `clickBehavior='link'` option. Wouldn't it be better to force that behavior when the dropdown toggle is an `<a>` tag with a non-empty `href` attribute?

**Comment by dwt** [comment]
That might be a workable path, but after thinking a bit about this, I think that it is better to be explicit than implicit, to avoid automatic surprising behavior changes as websites get updated.

**Comment by rbu** [comment]
@istvan-ujjmeszaros thanks for merging this (and the other PRs as well). It's frustrating sometimes, indeed :-)

I tend to agree with @dwt, it's not trivial to identify what the value of the href attribute is and if the user intended it to be a link. I haven't checked in a while, but I remember in the IE olden times, you had to set the attribute to at least `href="#"` for the link to activate. And then the $(a).attr('href') would be set to a full URL with scheme, hostname and whatnot.

**Comment by istvan-ujjmeszaros** [comment]
But using dropdowns with anchors aren't supported in Bootstrap (you can see in the bs4 plugin demo that there is even a gradient on the linked dropdown), so I can't imagine why would someone use it previously.
In the other hand, using link in the dropdown toggle is a special case, so it may be better to enforce the explicit setting.

**Comment by rbu** [comment]
I'm actually still using this with Bootstrap 3 and haven't checked if this works with 4 yet. Dropdowns on Links work fine there.

**Pull request merged**
